name: Pre Release

on:

  pull_request:
    branches:
      - "main"

jobs:
  prerelease:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: "Select Xcode 12.5.1"
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "12.5.1"

      - name: "Setup Git Access"
        run: |
          git config --global url."https://${{ secrets.ACCESS_TOKEN }}@github".insteadOf https://github

      - name: "Archive Package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "bundle exec rake 'package[-alpha.'$(date +%Y%m%d%H%M%S)']'"

      - name: "Release Package"'
        env:
'          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec rake 'release[${{ github.event.pull_request.head.ref }}]'